version: '3.5'

networks:
  network-zabbix:
    driver: bridge

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    command: 
      - mysqld
      - --character-set-server=utf8
      - --collation-server=utf8_bin
      - --default-authentication-plugin=mysql_native_password
    networks:
      - network-zabbix
    ports:
      - '3306:3306'
    volumes:
      #- ./zbx_env/var/lib/mysql:/var/lib/data:rw #sql5.0
      - ./zbx_env/var/lib/mysql:/var/lib/mysql:rw #sql8.0
      #- /etc/localtime:/etc/localtime:ro
      #- './zbx_env/var/lib/mysql:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=zabbix123qwe.# Troque a senha
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix123qwe. # Troque a senha
   # env_file:
   #  - .env_db_mysql
   # secrets:
    #  - MYSQL_USER
    #  - MYSQL_PASSWORD
    #  - MYSQL_ROOT_PASSWORD
    user: root
    stop_grace_period: 1m
    restart: always
  
  db_data_mysql:
    image: busybox
    volumes:
      - ./zbx_env/var/lib/mysql:/var/lib/mysql:rw
      - /etc/localtime:/etc/localtime:ro
  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-mysql:ubuntu-5.0.1
    networks:
      - network-zabbix
    links:
      - mysql
    restart: always
    ports:
      - '10051:10051'
    volumes:
      - ./zbx_env/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
      - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
      - ./zbx_env/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
      - ./zbx_env/var/lib/zabbix/snmptraps:/var/lib/zabbix/snmptraps:ro
      - /etc/localtime:/etc/localtime:ro
    # Configurações zabbix server
    environment:
      - DB_SERVER_HOST=mysql
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=carryontech
      # ZBX_LISTENIP=
      # ZBX_HISTORYSTORAGEURL=http://elasticsearch:9200/ # Available since 3.4.5
      # ZBX_HISTORYSTORAGETYPES=uint,dbl,str,log,text # Available since 3.4.5
      # ZBX_DBTLSCONNECT=require # Available since 5.0.0
      # ZBX_DBTLSCAFILE=/run/secrets/root-ca.pem # Available since 5.0.0
      # ZBX_DBTLSCERTFILE=/run/secrets/client-cert.pem # Available since 5.0.0
      # ZBX_DBTLSKEYFILE=/run/secrets/client-key.pem # Available since 5.0.0
      # ZBX_DBTLSCIPHER= # Available since 5.0.0
      # ZBX_DBTLSCIPHER13= # Available since 5.0.0
      # ZBX_DEBUGLEVEL=3
      # ZBX_STARTPOLLERS=5
      # ZBX_IPMIPOLLERS=0
      # ZBX_STARTPREPROCESSORS=3 # Available since 3.4.0
      # ZBX_STARTPOLLERSUNREACHABLE=1
      # ZBX_STARTTRAPPERS=5
      # ZBX_STARTPINGERS=1
      # ZBX_STARTDISCOVERERS=1
      # ZBX_STARTHTTPPOLLERS=1
      # ZBX_STARTTIMERS=1
      # ZBX_STARTESCALATORS=1
      # ZBX_STARTALERTERS=3 # Available since 3.4.0
      # ZBX_JAVAGATEWAY_ENABLE=true
      # ZBX_JAVAGATEWAY=zabbix-java-gateway
      # ZBX_JAVAGATEWAYPORT=10052
      # ZBX_STARTJAVAPOLLERS=5
      - ZBX_STARTVMWARECOLLECTORS=0
      - ZBX_VMWAREFREQUENCY=60
      - ZBX_VMWAREPERFFREQUENCY=60
      - ZBX_VMWARECACHESIZE=8M
      - ZBX_VMWARETIMEOUT=10
      # ZBX_ENABLE_SNMP_TRAPS=true
      # ZBX_SOURCEIP=
      # ZBX_HOUSEKEEPINGFREQUENCY=1
      # ZBX_MAXHOUSEKEEPERDELETE=5000
      # ZBX_SENDERFREQUENCY=30
      # ZBX_CACHESIZE=8M
      # ZBX_CACHEUPDATEFREQUENCY=60
      # ZBX_STARTDBSYNCERS=4
      # ZBX_HISTORYCACHESIZE=16M
      # ZBX_HISTORYINDEXCACHESIZE=4M
      # ZBX_TRENDCACHESIZE=4M
      # ZBX_VALUECACHESIZE=8M
      # ZBX_TIMEOUT=4
      # ZBX_TRAPPERIMEOUT=300
      # ZBX_UNREACHABLEPERIOD=45
      # ZBX_UNAVAILABLEDELAY=60
      # ZBX_UNREACHABLEDELAY=15
      # ZBX_LOGSLOWQUERIES=3000
      # ZBX_EXPORTFILESIZE=
      # ZBX_STARTPROXYPOLLERS=1
      # ZBX_PROXYCONFIGFREQUENCY=3600
      # ZBX_PROXYDATAFREQUENCY=1
      # ZBX_LOADMODULE="dummy1.so,dummy2.so,dummy10.so"
      # ZBX_TLSCAFILE=
      # ZBX_TLSCRLFILE=
      # ZBX_TLSCERTFILE=
      # ZBX_TLSKEYFILE=
    depends_on:
      - mysql
    #env_file:
    #  - .env_db_mysql
    #  - .env_srv
    #secrets:
    #  - MYSQL_USER
    #  - MYSQL_PASSWORD
    #  - MYSQL_ROOT_PASSWORD
  
    user: root
    depends_on:
      - mysql

  zabbix-frontend:
    container_name: zabbix-frontend
    image: zabbix/zabbix-web-apache-mysql:ubuntu-5.0.1
    networks:
      - network-zabbix
    links:
      - mysql
    restart: always
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
    #  - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./zbx_env/etc/ssl/apache2:/etc/ssl/apache2:ro
    #env_file:
    #  - .env_db_mysql
    #  - .env_web
    #secrets:
    #  - MYSQL_USER
    #  - MYSQL_PASSWORD
    environment:
      - DB_SERVER_HOST=mysql
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=carryontech
      - PHP_TZ=America/Sao_Paulo
      # ZBX_SERVER_HOST=zabbix-server
      # ZBX_SERVER_PORT=10051
      # ZBX_SERVER_NAME=Composed installation
      # ZBX_DB_ENCRYPTION=true # Available since 5.0.0
      # ZBX_DB_KEY_FILE=/run/secrets/client-key.pem # Available since 5.0.0
      # ZBX_DB_CERT_FILE=/run/secrets/client-cert.pem # Available since 5.0.0
      # ZBX_DB_CA_FILE=/run/secrets/pgsql-ca.pem # Available since 5.0.0
      # ZBX_DB_VERIFY_HOST=false # Available since 5.0.0
      # ZBX_DB_CIPHER_LIST= # Available since 5.0.0
      # ZBX_HISTORYSTORAGEURL=http://elasticsearch:9200/ # Available since 3.4.5
      # ZBX_HISTORYSTORAGETYPES=['uint', 'dbl', 'str', 'text', 'log'] # Available since 3.4.5
      # ENABLE_WEB_ACCESS_LOG=true
      # ZBX_MAXEXECUTIONTIME=600
      # ZBX_MEMORYLIMIT=128M
      # ZBX_POSTMAXSIZE=16M
      # ZBX_UPLOADMAXFILESIZE=2M
      # ZBX_MAXINPUTTIME=300
      # ZBX_SESSION_NAME=zbx_sessionid
      # Timezone one of: http://php.net/manual/en/timezones.php
      
    user: root
    depends_on:
      - mysql
    
  grafana:
    container_name: grafana
    image: grafana/grafana
    networks:
      - network-zabbix
    links:
      - mysql
      - zabbix-server
    restart: always
    ports:
      - '3000:3000'
    environment: 
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app,grafana-worldmap-panel,grafana-piechart-panel,grafana-clock-panel,aceiot-svg-panel,farski-blendstat-panel,savantly-heatmap-panel,ayoungprogrammer-finance-datasource,grafana-worldmap-panel
    depends_on:
      - mysql
      - zabbix-server
  zabbix-agent:
    container_name: zabbix-agent
    image: zabbix/zabbix-agent2:alpine-5.0.1
    user: root
    networks:
      - network-zabbix
    links:
      - zabbix-server
    restart: always
    privileged: true
    volumes:
      - /var/run:/var/run
      - ./zbx_env/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
      - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
    ports:
    # Zabbix_Agent
      - '161:161'
    - '10050:10050'
    # Zabbix_Agent SNMP
      - '161:161/udp'

    environment:
      - ZBX_HOSTNAME=Zabbix server
      - ZBX_SERVER_HOST=127.0.0.1
#secrets:
#   MYSQL_USER:
#   file: ./.MYSQL_USER
#   MYSQL_PASSWORD:
#   file: ./.MYSQL_PASSWORD
#   MYSQL_ROOT_PASSWORD:
#   file: ./.MYSQL_ROOT_PASSWORD
